admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

go_t:
    resource: "@GoTBundle/Resources/config/routing.yml"
    prefix:   /

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
