blogger_blog_list:
    path: /
    defaults: { _controller: GoTBundle:Blog:list }

blogger_blog_show:
    path: /show/{id}
    defaults: { _controller: GoTBundle:Blog:show }

blogger_blog_seasons:
    path: /season/
    defaults: { _controller: GoTBundle:Season:list }