<?php

namespace GoTBundle\Entity;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{
}
