<?php

namespace GoTBundle\Entity;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllHouses($limit = null)
	{
		$qh = $this->createQueryBuilder('h')->select('h')->addOrderBy('h.name', 'ASC');

		if (false === is_null($limit))
			$qh->setMaxResults($limit);

		return $qh->getQuery()->getResult();
	}
}
