<?php

namespace GoTBundle\Entity;

/**
 * PersonajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonajeRepository extends \Doctrine\ORM\EntityRepository
{
}
