<?php

namespace GoTBundle\Entity;

/**
 * PersonajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonajeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllPersonajes($limit = null)
	{
		$qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.name', 'ASC');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}

	public function getPersonajesForHouse($houseId)
	{
		$qh = $this->createQueryBuilder('p')->select('p')->where('p.house = :house_id')->addOrderBy('p.name')->setParameter('house_id', $houseId);

		return $qh->getQuery()->getResult();
	}
}
