<?php

namespace GoTBundle\Entity;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
		public function getAllSeasons($limit = null)
	{
		$qs = $this->createQueryBuilder('s')->select('s')->addOrderBy('s.id', 'ASC');

		if (false === is_null($limit))
			$qs->setMaxResults($limit);

		return $qs->getQuery()->getResult();
	}
}

