<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9vx7da9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9vx7da9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9vx7da9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9vx7da9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9vx7da9\appDevDebugProjectContainer(array(
    'container.build_hash' => '9vx7da9',
    'container.build_id' => 'f0eb6935',
    'container.build_time' => 1542638843,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9vx7da9');
