<?php

namespace Proxies\__CG__\GoTBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Season extends \GoTBundle\Entity\Season implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'personajes', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'id', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'name', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'fecha', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'capitulos', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'resumen'];
        }

        return ['__isInitialized__', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'personajes', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'id', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'name', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'fecha', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'capitulos', '' . "\0" . 'GoTBundle\\Entity\\Season' . "\0" . 'resumen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Season $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacters', []);

        return parent::getCharacters();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapitulos($capitulos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapitulos', [$capitulos]);

        return parent::setCapitulos($capitulos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapitulos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapitulos', []);

        return parent::getCapitulos();
    }

    /**
     * {@inheritDoc}
     */
    public function setResumen($resumen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResumen', [$resumen]);

        return parent::setResumen($resumen);
    }

    /**
     * {@inheritDoc}
     */
    public function getResumen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResumen', []);

        return parent::getResumen();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonaje(\GoTBundle\Entity\Personaje $personaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonaje', [$personaje]);

        return parent::addPersonaje($personaje);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonaje(\GoTBundle\Entity\Personaje $personaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonaje', [$personaje]);

        return parent::removePersonaje($personaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonajes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonajes', []);

        return parent::getPersonajes();
    }

}
